
# adapted from https://github.com/magnars/dash.el/blob/master/.travis.yml

language: emacs-lisp

before_install:
  
  # PPA for stable Emacs packages, only up to 24.3
  # https://launchpad.net/~cassou/+archive/ubuntu/emacs
  - sudo add-apt-repository -y ppa:cassou/emacs
  
  # PPA for Emacs 24.4
  # https://launchpad.net/~andreas-h/+archive/ubuntu/emacs
  # - ? sudo deb http://ppa.launchpad.net/andreas-h/emacs/ubuntu trusty main
  
  # PPA for Emacs nightlies, 25.1?
  # https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa
  # - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  
  # Update and install the Emacs for our environment
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el

env:
  # - EMACS=emacs23
  - EMACS=emacs24
  # - EMACS=emacs-snapshot


email:
  - bburns.km@gmail.com


script:
  make test



